### ISSUE TITLE
incorporate passport code to current project

### ISSUE THREAD

**Issue by yusungsamuel** [SophM/APParent#28]
In Progress: 
- Add passport authentication function to route file that contains the user login and signup post request route.
- adjust codes so that it uses controller because we did not have a controller in previous project
- Require passport, express-session and add the following code to  in server.js
- Add passport, express-session, bcryptjs, and passport-local to package.json

`app.use(session({
  key: 'user_sid',
  secret: 'goN6DJJC6E287cC77kkdYuNuAyWnz7Q3iZj8',
  resave: true,
  saveUninitialized: false,
  cookie: {
      expires: 600000,
      httpOnly: false
  }
}));

// Passport middleware
app.use(passport.initialize());
app.use(passport.session());`

Finished: 
- Add passport.js file to config folder.
- Add hashing function to parent model.

**Comment by NVK2016** [comment]
Done
